#!/bin/zsh

# Interactive dialog to choose which packages to update

START_TARGET="Targets"
END_TARGET="Total Download"

tf=`mktemp`
pacman -Qu > $tf
start=$(grep -n $START_TARGET $tf | cut -d':' -f1)
end=$(grep -n $END_TARGET $tf | cut -d':' -f1)
lines=$(echo $end-$start-2 | bc)
grep $START_TARGET -A$lines
