#!/usr/bin/ruby

# == Description
# commify - Converts a plain number into it's commified version.
# == Usage
#	commify 1234
#	echo 1234 | commify

# Commify a number. Works with floats as well!
class Numeric
	def commify(delim = ',')
		#self.to_s.reverse.gsub(/(\d\d\d)(?=\d)(?!\d*\.)/,'\1,').reverse
		self.to_s.reverse.gsub(%r{([[:digit:]]{3})(?=[[:digit:]])(?![[:digit:]]*\.)}, "\\1#{delim}").reverse
	end
end

if __FILE__ == $0
	n = (ARGV[0] or $stdin.gets)
	if ["-h", "--help", "-help"].include? n
		require 'rdoc/usage'
		RDoc.usage
	end
	puts n.to_i.commify
end
