#!/usr/bin/ruby

# Given a path to a RFC email message (supported by Ruby's mailread lib),
# and using the College Board's plain text email format, downloads the day's
# SAT question to $HOME/Downloads/SAT_of_the_Day/

require 'mailread'
require 'uri'
require 'fileutils'

puts "Downloading SAT QotD from #{ARGV[0]}"
email = ARGV[0] # Claws-Mail passes this as %F in the processing rules
mailr = Mail.new(email)
url = mailr.body[3].chomp
puts "Set up, calling 'wget -E -k'..."

FileUtils::cd("#{ENV['HOME']}/Downloads/SAT_of_the_Day")
puts `wget -E -k #{url}`
pp Dir['apps*/**']
path = Dir['apps*/*/*'].first
puts "Done, moving html file (found at #{path})..."
id = path.split('=')[1]
puts "FileUtils::mv(path, 'sat_qotd_#{id}_#{Date.today.strftime('%d%b%Y')}.html')"
FileUtils::mv(path, "sat_qotd_#{id}_#{Date.today.strftime('%d%b%Y')}.html")
puts "Deleting..."
FileUtils::mv(Dir['q*'].first, "sat_qotd_#{id}_#{Date.today.strftime('%d%b%Y')}.html")
FileUtils::rm_rf(Dir['apps*'].first)
