#!/bin/sh

if [ -d "$HOME/bin" ] ; then
   export PATH="$HOME/bin:$PATH"
fi

args="-i -f"
# TODO: font & colors. From xrdb?
if [ -x /usr/bin/yeganesh ] ; then
   dbin='yeganesh'
   args="-f -p dmenu_run -- $args"
else
   dbin='dmenu'
fi

exe=`dmenu_path | /usr/bin/$dbin $args $@` && exec $exe
