#!/usr/bin/python

import sys
sys.path.append("/usr/bin")
import /usr/bin/gcalcli

class CLR:
    useColor = True

    def __str__(self):
        if self.useColor: return "${color #"+self.color+"}"
        else: return ""

class CLR_NRM(CLR):   color = "dddddd"
class CLR_BLK(CLR):   color = "000000"
class CLR_BRBLK(CLR): color = "222222" # light gray-ish?
class CLR_RED(CLR):   color = "dd0000"
class CLR_BRRED(CLR): color = "ff0000"
class CLR_GRN(CLR):   color = "00dd00"
class CLR_BRGRN(CLR): color = "00ff00"
class CLR_YLW(CLR):   color = "dd00dd"
class CLR_BRYLW(CLR): color = "ff00ff"
class CLR_BLU(CLR):   color = "0000dd"
class CLR_BRBLU(CLR): color = "0000ff"
class CLR_MAG(CLR):   color = "dd00dd"
class CLR_BRMAG(CLR): color = "ff00ff"
class CLR_CYN(CLR):   color = "00dddd"
class CLR_BRCYN(CLR): color = "00ffff"
class CLR_WHT(CLR):   color = "dddddd"
class CLR_BRWHT(CLR): color = "ffffff"
