#!/usr/bin/ruby

# Adds a series of podcasts from a OPML file to gpodder using "gpodder -a"

if ARGV.include? "--help" or ARGV.include? "-h" or !ARGV[0]
	puts <<HELP
gpod_opml [-h,--help] OPML
gpod_opml adds a series of podcasts from a OPML file (given as the first parameter) to gpodder using "gpodder -a"
	-h, --help	This message
HELP
	exit 0
end

require 'open-uri'
require 'rubygems'
require 'libxml'
XML = LibXML::XML
Gpodder_Opml = "#{ENV['HOME']}/.config/gpodder/channels.opml"

opml = XML::Parser.string(open(ARGV[0]).read).parse
gpod = XML::Document.file(Gpodder_Opml)
body = gpod.find_first("//body")
opml.find_first("//body").find("outline").each do |podcast|
	puts "Adding: #{podcast['text']}"
	body << podcast.copy(true) unless body.find_first("outline[@xmlUrl='#{podcast['xmlUrl']}']")
end
gpod.save(Gpodder_Opml)
#`gpodder -a #{podcast['xmlUrl']}`
system('gpodder -u')
