#!/bin/zsh

# Updates the Applications menu used in my Openbox menu using mmaker
APPS_XML="$HOME/.config/openbox/applications.xml"

mmaker -cpt xterm openbox | sed 's/id="root-menu".*/id="apps-menu" label="Applications">/' | head -n-9 | tail -n+3 | sed "s/^\t//" > $APPS_XML
echo "\t</menu>" >> $APPS_XML

#echo "<openbox_pipe_menu>" > $APPS_XML
#mmaker -cpt xterm openbox | grep -P "^\t\t" | sed "s/^\t\t/\t/" | head -n-7 >> $APPS_XML
#echo "</openbox_pipe_menu>" >> $APPS_XML
