#!/usr/bin/ruby

unless ARGV[0] or ARGV.include? "-h" or ARGV.include? "--help"
    puts "Missing required parmeter: Newgrounds Audio Portal ID"
    puts ""
    puts "Usage: #{File.basename($0)} ID"
    exit 1
end

require 'nokogiri'
require 'open-uri'
Url_Listen   = "http://www.newgrounds.com/audio/listen/%s"
Url_Download = "http://www.newgrounds.com/audio/download/%s"

puts "Downloading song ##{ARGV[0]}..."
doc = Nokogiri::HTML(open(Url_Listen % ARGV[0]))

puts "finding title..."
title = doc.css("#leftcol h1.view").first.content

puts "finding author..."
author = doc.css(".author a").first.content

puts <<INFO
 Title: #{title}
Author: #{author}
INFO

__END__
open(Url_Download % ARGV[0]) do |song|
    File.open(File.basename('newgrounds.mp3'), "wb") do |local|
        local.write(song.read)
    end
end
