#!/bin/sh

# Make bash split on ':', not \n
IFS=:

# Search through each directory
for dir in $PATH
do
	cd "$dir" &&
	for file in *
	do
		# Test if the file isn't executable
		test ! -x "$file" -a "$file" != "*" && echo "$dir/$file"
	done
done | sort -u
