#!/bin/bash
# Utility to generate a list of all files that are not part of a package
# Author: Spider.007 / Sjon

TMPDIR=`mktemp -d`
if [[ -z $TMPDIR ]] ; then
    echo "Could not create temporary directory." >&2
    exit 1
fi
FILTER=$(sed '1,/^## FILTERED/d' $0 | tr '\n' '|')
FILTER=${FILTER%|}

cd $TMPDIR
find /bin /boot /etc /lib /opt /sbin /usr /var | sort -u > full
pacman -Ql | tee owned_full | cut -d' ' -f2- | sed 's/\/$//' | sort -u > owned

grep -Ev "^($FILTER)" owned > owned- && mv owned- owned

echo -e '\033[1mOwned, but not found:\033[0m'
comm -13 full owned | while read entry
do
    echo [`grep --max-count=1 $entry owned_full|cut -d' ' -f1`] $entry
done | sort

grep -Ev "^($FILTER)" full > full- && mv full- full

echo -e '\n\033[1mFound, but not owned:\033[0m'
comm -23 full owned

#cd /tmp/ && rm -R $TMPDIR
# Clean up
[[ -n $TMPDIR ]] && rm $TMPDIR/{full,owned,owned_full} && rmdir $TMPDIR

exit 0

## FILTERED FILES / PATHS ##
/boot/grub
/dev
/etc/X11/xdm/authdir
/home
/media
/mnt
/proc
/root
/srv
/sys
/tmp
/var/abs
/var/cache
/var/games
/var/log
/var/lib/pacman
/var/lib/mysql
/var/run
/var/tmp
