#!/bin/zsh

# XDG-Open's called script, this will run firefox/elinks depending on DISPLAY

if [ -e "$(pwd)/${1}" ] ; then
	url="file://$(pwd)/${1}"
else
	url="${1}"
fi

if [ $DISPLAY ] ; then
	firefox.sh $url
	notify-send -i "/usr/share/icons/hicolor/48x48/apps/firefox.png" \
		"firefox-bin" "Firefox has finally closed"
else
	pid=$(pidof elinks)
	if [ ! -z $pid ] ; then
		echo "pidof elinks"
		elinks -remote "${url}" > /dev/null
	else
		echo "new elinks"
		elinks $url > /dev/null
	fi
fi
