#!/bin/sh

# Comment out the following 2 lines and uncomment the third line to manually set
# the port of the local ssh server instead of attempting to automatically set it.
#export SSH_PORT=$(grep '^Port' /etc/ssh/sshd_config | sed 's/^Port \([0-9]*\)/\1/')
export SSH_PORT=22 # manually set the port instead of auto-detecting it

export REMOTE_HOST=me # Any valid ssh host can go here, including aliases.
export REMOTE_PORT=1615 # the port to use on the remote server

ssh ${REMOTE_HOST} -R ${REMOTE_PORT}:localhost:${SSH_PORT}

