#!/bin/zsh

# Teamspeak launcher
cd "${HOME}/Games/TeamSpeak2RC2" # This is where I set the installer to extract
# to. Change this to suit your installation
./TeamSpeak &
#while [ -z "$(pgrep -u $USER TeamSpeak)" ] ; do sleep 1 ; done
#cd "client_sdk"
#./tsControl CONNECT "TeamSpeak://208.122.34.40:8769?nickname=|ALPHA|FriarFoaly?loginname=zenix?password=c1235748uats" &
#./tsControl CONNECT "TeamSpeak://ts4.gamservers.com:8782?nickname=|ALPHA|FriarFoaly?password=" &

