#!/bin/zsh
#

# Change to your ssh server information
SSHSERVER=colin@192.168.1.14

# Change this to the base path of the installation on your remote server.
# For instance, if your WordPress or other application is installed in 
# /var/www/remote/directory/, then you should add that path here
RDIR=/pub/my_site/public
if [ -n "$2" ] ; then
	RDIR=$2
	#SSHSERVER=root@192.168.1.4
fi

# Change this to the base path of your application install on your local
# machine. For instance, if your application is installed in /var/www
# then you should be fine. Just remember to escape all / with a \ as shown.
#LDIR='\/home\/Projects\/Ruby'

#scp -r -P 21 $1 $SSHSERVER:$RDIR`pwd|sed "s/${LDIR}//"`/`echo $1|sed 's/.*\///'`

scp -r -P 21 $1 $SSHSERVER:$RDIR
