#!/bin/zsh

VIM="vim"
#GUI="false"
#case "$TERM" in
#	*xterm*|rxvt|(dt|k|E)term)
#		GUI="true"
#	;;
#esac

# Test for X.org & if gvim exists
#[ $DISPLAY ] && which gvim > /dev/null && VIM="$(which gvim)"

# Only update when gvim is acutally ran, not every time
#if [ -e "${HOME}/.vim/guirc" -a -n $DISPLAY ]; then
#	if [ "${HOME}/.vimrc" -nt "${HOME}/.gvimrc" ]; then
#		cat "${HOME}/.vimrc" > "${HOME}/.gvimrc"
#		cat "${HOME}/.vim/guirc" >> "${HOME}/.gvimrc"
#	fi
#fi
# Commented out because I don't really use the gui features anyways...

#if [ $(vim --serverlist | grep -P "^VIM$") ]; then
if [ -n "$(ps wwaux | grep -P '/usr/bin/[g]*vim' )" ];then
	$VIM --servername VIM --remote-tab $@
else
	$VIM --servername VIM -p $@
fi
