#!/usr/bin/ruby

# Downloads Weather.com's Hour-by-hour forecast and strips links, putting
# the resulting HTML in $HOME/weather_hourbyhour.html

require 'open-uri'

Zip = ARGV[0] || 20877 # The zip code to fetch weather for
path = "#{ENV['HOME']}/weather_hourbyhour.html"
# Replace 20877 with the zip code of choice
url = "http://www.weather.com/weather/hourbyhour/%s" % Zip
a = open(url).read.split("\n")
# Pulls everything from <!-- content --> to the end of the 2nd table (which contains the "Last Updated" bit)
s = a[a.index(a.grep(/<!-- content -->/).first)..a.index(a.grep(/Last Updated/).first)+2].map{|b| b.strip}.join("\n")
f = File.open("#{path}", 'w')
# Strip all links, except a few which are <A> instead of <a>, and strip the
# bold '>' left over from the "Next >" link
s = "<h4>Weather forecast hour by hour for #{Zip}</h4>\n#{s}"
f.write s.gsub(/<a.*?>.*?<\/a>/, '').gsub(/<B>\s+>\s+<\/B>/, '')
f.close
puts "Hour-by-Hour weather forecast saved to #{path}"
