#!/bin/sh

# From http://www.commandlinefu.com/commands/view/4216/view-the-newest-xkcd-comic

source="$(curl -s http://xkcd.com/)"

#display $(echo "$source"|grep -Po '(?<=")http://imgs.xkcd.com/comics/[^"]+(png|jpg)');
echo "$source"|grep -Po '(?<=")http://imgs.xkcd.com/comics/[^"]+(png|jpg)'
echo "$source" | awk '/<img src="http:\/\/imgs\.xkcd\.com\/comics\/.*?" title=.*/{gsub(/^.*title=.|".*?$/,"");print}';
